FROM ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.5.1}

USER root

RUN apt-get update && \
    apt-get install -y default-libmysqlclient-dev gcc

USER airflow

RUN pip install mysqlclient && \
    pip install apache-airflow-providers-microsoft-azure azure.servicebus
