version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admpw
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: userpw
    volumes:
      - ./mysql-db-volume:/var/lib/mysql  # Persistent storage for MySQL data
      - ./sqls/init.sql:/docker-entrypoint-initdb.d/init.sql  # Copy init.sql for initialization
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmpw"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "3306:3306"
    networks:
      - shared-network

  flask-app:
    image: flask-custom:1.0
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./:/app  # Mount the current directory to /app in the container
    networks:
      - shared-network

networks:
  shared-network:
    external: true
